'use strict';
/**
 * gen-drift.js — reads enum-mysql-out.txt and enum-pg-out.txt,
 * diffs them, and writes schema-drift.sql
 */
const fs = require('fs');
const path = require('path');

// ── Read files ────────────────────────────────────────────────────────────────
const mysqlRaw = fs.readFileSync(path.join(__dirname, 'enum-mysql-out.txt'), 'utf8');
const pgRaw    = fs.readFileSync(path.join(__dirname, 'enum-pg-out.txt'), 'utf8');

function extractLine(text, prefix) {
  const line = text.split('\n').find(l => l.startsWith(prefix));
  if (!line) throw new Error(`Missing line starting with: ${prefix}`);
  return line.slice(prefix.length).trim();
}

const mysqlTables  = JSON.parse(extractLine(mysqlRaw, 'TABLES:'));
const mysqlColumns = JSON.parse(extractLine(mysqlRaw, 'COLUMNS:'));
const pgTables     = JSON.parse(extractLine(pgRaw, 'PG_TABLES:'));
const pgColumns    = JSON.parse(extractLine(pgRaw, 'PG_COLUMNS:'));

console.log(`MySQL tables: ${mysqlTables.length}`);
console.log(`PG tables:    ${pgTables.length}`);

// ── Build maps ────────────────────────────────────────────────────────────────
// mysqlColMap: table → [column info objects]
const mysqlColMap = new Map();
for (const c of mysqlColumns) {
  const tbl = c.TABLE_NAME;
  if (!mysqlColMap.has(tbl)) mysqlColMap.set(tbl, []);
  mysqlColMap.get(tbl).push(c);
}

// pgColSet: "table.column" set
const pgColSet = new Set();
for (const c of pgColumns) {
  pgColSet.add(`${c.table_name}.${c.column_name}`);
}
const pgTableSet = new Set(pgTables);

// ── Type conversion ───────────────────────────────────────────────────────────
function mysqlToPgType(col) {
  const dtype = (col.DATA_TYPE || '').toLowerCase();
  const ctype = (col.COLUMN_TYPE || '').toLowerCase();
  const extra = (col.EXTRA || '').toLowerCase();
  const prec  = col.NUMERIC_PRECISION;
  const scale = col.NUMERIC_SCALE;
  const charLen = col.CHARACTER_MAXIMUM_LENGTH;

  // AUTO_INCREMENT → identity handled separately (only for PK)
  if (extra.includes('auto_increment')) return 'bigint generated by default as identity';

  if (dtype === 'bit' || ctype === 'tinyint(1)') return 'boolean';
  if (dtype === 'tinyint') return 'smallint';
  if (dtype === 'smallint') return 'smallint';
  if (dtype === 'mediumint') return 'int';
  if (dtype === 'int' || dtype === 'integer') return 'int';
  if (dtype === 'bigint') return 'bigint';
  if (dtype === 'float') return 'double precision';
  if (dtype === 'double') return 'double precision';
  if (dtype === 'decimal' || dtype === 'numeric') {
    if (prec != null && scale != null) return `numeric(${prec},${scale})`;
    return 'numeric';
  }
  if (dtype === 'datetime' || dtype === 'timestamp') return 'timestamptz';
  if (dtype === 'date') return 'date';
  if (dtype === 'time') return 'time';
  if (dtype === 'year') return 'smallint';
  if (dtype === 'char') return charLen ? `char(${charLen})` : 'char';
  if (dtype === 'varchar') return charLen ? `varchar(${charLen})` : 'varchar(255)';
  if (dtype === 'tinytext') return 'text';
  if (dtype === 'text') return 'text';
  if (dtype === 'mediumtext') return 'text';
  if (dtype === 'longtext') return 'text';
  if (dtype === 'enum') return 'text';
  if (dtype === 'set') return 'text';
  if (dtype === 'json') return 'jsonb';
  if (dtype === 'tinyblob' || dtype === 'blob' || dtype === 'mediumblob' || dtype === 'longblob') return 'bytea';
  if (dtype === 'binary' || dtype === 'varbinary') return 'bytea';
  // fallback
  return 'text';
}

function colDDL(col) {
  const name  = col.COLUMN_NAME;
  const extra = (col.EXTRA || '').toLowerCase();
  const nullable = col.IS_NULLABLE === 'YES';

  // identity columns don't need nullability/default
  if (extra.includes('auto_increment')) {
    return `"${name}" bigint generated by default as identity primary key`;
  }

  const pgType = mysqlToPgType(col);
  const nullPart = nullable ? ' DEFAULT NULL' : ' NOT NULL';
  return `"${name}" ${pgType}${nullPart}`;
}

// ── Generate DDL ──────────────────────────────────────────────────────────────
const lines = [];
lines.push('-- schema-drift.sql — auto-generated by gen-drift.js');
lines.push(`-- MySQL tables: ${mysqlTables.length}  |  PG tables before: ${pgTables.length}`);
lines.push('');

const createdTables  = [];
const alteredTables  = [];

for (const table of mysqlTables) {
  const cols = mysqlColMap.get(table) || [];

  if (!pgTableSet.has(table)) {
    // ── CREATE TABLE ──────────────────────────────────────────────────────
    createdTables.push(table);
    lines.push(`-- ============================================================`);
    lines.push(`-- NEW TABLE: ${table}`);
    lines.push(`-- ============================================================`);
    lines.push(`CREATE TABLE IF NOT EXISTS "${table}" (`);
    const colDefs = cols.map(c => '  ' + colDDL(c));
    lines.push(colDefs.join(',\n'));
    lines.push(');');
    lines.push('');
  } else {
    // ── ALTER TABLE — add missing columns ────────────────────────────────
    const missingCols = cols.filter(c => !pgColSet.has(`${table}.${c.COLUMN_NAME}`));
    if (missingCols.length > 0) {
      alteredTables.push({ table, cols: missingCols.map(c => c.COLUMN_NAME) });
      lines.push(`-- ============================================================`);
      lines.push(`-- ALTER TABLE: ${table} — add ${missingCols.length} missing column(s)`);
      lines.push(`-- ============================================================`);
      for (const c of missingCols) {
        const extra = (c.EXTRA || '').toLowerCase();
        let def;
        if (extra.includes('auto_increment')) {
          // Skip auto_increment adds — PK already exists
          lines.push(`-- SKIP auto_increment column "${c.COLUMN_NAME}" (PK already defined)`);
          continue;
        }
        def = colDDL(c);
        lines.push(`ALTER TABLE "${table}" ADD COLUMN IF NOT EXISTS ${def};`);
      }
      lines.push('');
    }
  }
}

fs.writeFileSync(path.join(__dirname, 'schema-drift.sql'), lines.join('\n'), 'utf8');

console.log(`\nTables to CREATE: ${createdTables.length}`);
createdTables.forEach(t => console.log(`  + ${t}`));
console.log(`\nTables to ALTER:  ${alteredTables.length}`);
alteredTables.forEach(({ table, cols }) => console.log(`  ~ ${table}: +${cols.join(', +')}`));
console.log('\nWrote schema-drift.sql');
